In [1]:
# Artificial Neural Network

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
tf.__version__

'2.15.0'

In [5]:
dataset = pd.read_csv('./Churn_Modelling.csv')

In [6]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [7]:
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [9]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

X[:, 2] = le.fit_transform(X[:, 2])

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(
    transformers=[
        ('encoder', OneHotEncoder(), [1]),
    ],
    remainder='passthrough',
)

X = np.array(
    ct.fit_transform(X)
)

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=0)


In [16]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()

X_train = ss.fit_transform(X_train)
X_test = ss.transform(X_test)

In [17]:
ann = tf.keras.models.Sequential()

In [18]:
# Input layer

ann.add(
    tf.keras.layers.Dense(
        units=6,
        activation='relu',
    )
)

In [19]:
# Hidden layer

ann.add(
    tf.keras.layers.Dense(
        units=6,
        activation='relu'
    )
)

In [20]:
# Output layer

ann.add(
    tf.keras.layers.Dense(
        units=1,
        activation='relu',
    )
)

In [21]:
ann.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy'],
)

In [22]:
ann.fit(
    X_train, y_train,
    batch_size=50,
    epochs=10
)

Epoch 1/10


160/160 [==============================] - 8s 5ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 2/10
160/160 [==============================] - 1s 5ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 3/10
160/160 [==============================] - 1s 6ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 4/10
160/160 [==============================] - 1s 5ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 5/10
160/160 [==============================] - 1s 7ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 6/10
160/160 [==============================] - 1s 6ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 7/10
160/160 [==============================] - 1s 5ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 8/10
160/160 [==============================] - 1s 5ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 9/10
160/160 [==============================] - 1s 5ms/step - loss: 3.1467 - accuracy: 0.7960
Epoch 10/10
160/160 [==============================] - 1s 6ms/step - loss: 3.1467 - accuracy: 0.79

In [24]:
ann.predict(
    ss.transform([[ 1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000 ]])
) > .5

1/1 [==============================] - 1s 621ms/step


array([[False]])

In [26]:
y_pred = ann.predict(X_test)
y_pred - y_pred > .5

print(
    np.concatenate(
        (
            y_pred.reshape(-1, 1),
            y_test.reshape(-1, 1),
        ),
        1
    )
)

63/63 [==============================] - 0s 3ms/step
[[0. 0.]
 [0. 1.]
 [0. 0.]
 ...
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [28]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)

accuracy_score(y_test, y_pred)

[[1595    0]
 [ 405    0]]


0.7975