In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [4]:
df = pd.read_csv('./Iris.csv')

X = df.iloc[:, 1:4].values
y = df.iloc[:, 4].values

df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [5]:
pca = PCA(n_components=2)

X = pca.fit_transform(X)

In [6]:
X

array([[-2.49120628,  0.32842889],
       [-2.52490896, -0.17066072],
       [-2.71231754, -0.1299729 ],
       [-2.55917263, -0.30820093],
       [-2.53908694,  0.33875833],
       [-2.13468115,  0.75710223],
       [-2.67741646, -0.06542263],
       [-2.42970863,  0.17022981],
       [-2.71111913, -0.56451225],
       [-2.44212721, -0.11643989],
       [-2.30024464,  0.64866055],
       [-2.41609165,  0.02236017],
       [-2.5639241 , -0.23458107],
       [-3.03394159, -0.49409597],
       [-2.44572244,  1.18717814],
       [-2.24525786,  1.36017008],
       [-2.50127021,  0.83721802],
       [-2.49120628,  0.32842889],
       [-2.00877021,  0.87461349],
       [-2.42615558,  0.53114929],
       [-2.09035355,  0.38585331],
       [-2.41729006,  0.45689951],
       [-3.06173656,  0.16319272],
       [-2.19853344,  0.11984248],
       [-2.14114985, -0.03772667],
       [-2.30259929, -0.14679827],
       [-2.33806137,  0.15020086],
       [-2.36054388,  0.37232029],
       [-2.44332562,

In [7]:
main_df = pd.DataFrame(data=X, columns=['principal component 1', 'principal component 2'])

main_df

principal component 1  principal component 2
0                -2.491206               0.328429
1                -2.524909              -0.170661
2                -2.712318              -0.129973
3                -2.559173              -0.308201
4                -2.539087               0.338758
..                     ...                    ...
145               1.659960               0.218806
146               1.364932              -0.368067
147               1.581929               0.090965
148               1.612716               0.156145
149               1.256191              -0.272528

[150 rows x 2 columns]

In [8]:
pca.components_

array([[ 0.39015139, -0.0886552 ,  0.91647267],
       [ 0.63920348,  0.74249784, -0.20028948]])

In [9]:
pca.explained_variance_

array([3.68651942, 0.24098081])

In [10]:
final_df = pd.concat(
    [
        main_df,
        df[['Species']]
    ],
    axis=1
)

In [11]:
final_df

principal component 1  principal component 2         Species
0                -2.491206               0.328429     Iris-setosa
1                -2.524909              -0.170661     Iris-setosa
2                -2.712318              -0.129973     Iris-setosa
3                -2.559173              -0.308201     Iris-setosa
4                -2.539087               0.338758     Iris-setosa
..                     ...                    ...             ...
145               1.659960               0.218806  Iris-virginica
146               1.364932              -0.368067  Iris-virginica
147               1.581929               0.090965  Iris-virginica
148               1.612716               0.156145  Iris-virginica
149               1.256191              -0.272528  Iris-virginica

[150 rows x 3 columns]