In [2]:
import numpy as np

In [3]:
np.__version__

'1.24.3'

In [4]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [5]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
a[0, 1:3]

array([2, 3])

In [9]:
np.where(a > 5, a, 0)

array([[0, 0, 0],
       [0, 0, 6],
       [7, 8, 9]])

In [11]:
a.shape

(3, 3)

In [13]:
b = np.array([[1,2,3], [4,5,6]])

In [14]:
np.reshape(b, (3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
np.reshape(b, (1, -1))

array([[1, 2, 3, 4, 5, 6]])

In [19]:
np.reshape(b, (1, -1))

array([[1, 2, 3, 4, 5, 6]])

In [20]:
np.reshape(b, (-1, 1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [21]:
a.ndim

2

In [22]:
a.dtype

dtype('int32')

In [23]:
c = np.array([[1,2,3],[4,5,6]], dtype=np.int32)

In [24]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
c.dtype

dtype('int32')

In [26]:
c.ndim

2

In [27]:
c.size

6

In [28]:
c.itemsize # size of each elements in bytes

4

In [29]:
np.arange(1, 20, step=3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [30]:
np.linspace(1, 2, num=5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [31]:
np.linspace(1, 20, num=7)

array([ 1.        ,  4.16666667,  7.33333333, 10.5       , 13.66666667,
       16.83333333, 20.        ])

In [32]:
np.linspace(1, 19, num=7)

array([ 1.,  4.,  7., 10., 13., 16., 19.])

In [33]:
np.ones(shape=(3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [34]:
np.zeros(shape=(2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [36]:
np.zeros((1,5), dtype=np.int8)

array([[0, 0, 0, 0, 0]], dtype=int8)

In [37]:
5 * np.ones((4, 5))

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [38]:
np.full((2,5), 7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [39]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
np.fliplr( np.eye(5) )

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [42]:
np.fliplr( np.eye(3) )

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [43]:
np.random.rand(3,2)

array([[0.90092388, 0.27606648],
       [0.38373414, 0.58680627],
       [0.55738711, 0.93851049]])

In [48]:
np.random.randint(1, 20, (3,4))

array([[11, 19, 13,  6],
       [ 7, 18,  7, 15],
       [19, 11,  7,  1]])