In [1]:
"""
Data Collection and Assembly
Data Preprocessing
Data Exploration and Visyalization
Model Building
Model Evaluation
"""

'\nData Collection and Assembly\nData Preprocessing\nData Exploration and Visyalization\nModel Building\nModel Evaluation\n'

In [2]:
"""
Importing the libraries
Importing the dataset
Missing values
Encoding categorical data
    Encoding the independent variable
    Encoding the dependent variable
Splitting the dataset into the training set and test set
Feature scaling
"""

'\nImporting the libraries\nImporting the dataset\nMissing values\nEncoding categorical data\n    Encoding the independent variable\n    Encoding the dependent variable\nSplitting the dataset into the training set and test set\nFeature scaling\n'

In [3]:
import numpy as np
import  pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

%matplotlib inline

In [ ]:
df = pd.read_csv('data.csv')
X = df.iloc[:, :-1].values # numpy.ndarray
y = df.ilco[:, -1].values

In [ ]:
df.info()

In [ ]:
df.columns

In [ ]:
X = df[['A', 'B']].values
y = df['P'].values

# Missing Values

df.isnull()
df.isnull().sum()

In [ ]:
df_dropna = df.copy()
df_dropna.dropna(inplace=True)

In [ ]:
df.shape

In [ ]:
df.fillna( df.mean() , inplace=True )

In [4]:
#

In [5]:
X = np.array([
    [12, 43, 61, 98 , 3],
    [12, 13, 1, 84 , 33],
    [1, 4, 11, 98 , 6],
])
y = np.array([
    [11, 7, 8]
])

In [6]:
X

array([[12, 43, 61, 98,  3],
       [12, 13,  1, 84, 33],
       [ 1,  4, 11, 98,  6]])

In [7]:
y

array([[11,  7,  8]])

In [10]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, :])
X[:, :] = imputer.transform(X[:, :])
# .fit_transform(
X

array([[12, 43, 61, 98,  3],
       [12, 13,  1, 84, 33],
       [ 1,  4, 11, 98,  6]])

# Missing Values