# Missing Values

In [2]:
import numpy as np

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(
    transformers=[
        (
            'encoder',
            OneHotEncoder(),
            [0]
        )
    ],
    remainder='passthrough'
)

X = np.array([
    [1,2,3,None,6,0,None],
    [1,None,3,1,6,0,4],
    [None,2,3,None,6,0,None],
])
y = np.array([
    1,2,3
])

X = np.array(ct.fit_transform(X))

In [6]:
import seaborn as sns

iris = sns.load_dataset('iris')

In [17]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(
    transformers=[
        (
            'some-random-name-like-encoder',
            OneHotEncoder(),
            [-1] # Which Column(s)
        )
    ],
    remainder='passthrough' # What should it do to the rest of the columns? -> passthrough
)

np.array(
    ct.fit_transform(
        iris.to_numpy()
    )
)

array([[1.0, 0.0, 0.0, ..., 3.5, 1.4, 0.2],
       [1.0, 0.0, 0.0, ..., 3.0, 1.4, 0.2],
       [1.0, 0.0, 0.0, ..., 3.2, 1.3, 0.2],
       ...,
       [0.0, 0.0, 1.0, ..., 3.0, 5.2, 2.0],
       [0.0, 0.0, 1.0, ..., 3.4, 5.4, 2.3],
       [0.0, 0.0, 1.0, ..., 3.0, 5.1, 1.8]], dtype=object)

In [19]:
import pandas as pd

pd.get_dummies(iris)

sepal_length  sepal_width  petal_length  petal_width  species_setosa  \
0             5.1          3.5           1.4          0.2            True   
1             4.9          3.0           1.4          0.2            True   
2             4.7          3.2           1.3          0.2            True   
3             4.6          3.1           1.5          0.2            True   
4             5.0          3.6           1.4          0.2            True   
..            ...          ...           ...          ...             ...   
145           6.7          3.0           5.2          2.3           False   
146           6.3          2.5           5.0          1.9           False   
147           6.5          3.0           5.2          2.0           False   
148           6.2          3.4           5.4          2.3           False   
149           5.9          3.0           5.1          1.8           False   

     species_versicolor  species_virginica  
0                 False              False  
1                 False              False  
2                 False              False  
3                 False              False  
4                 False              False  
..                  ...                ...  
145               False               True  
146               False               True  
147               False               True  
148               False               True  
149               False               True  

[150 rows x 7 columns]

In [22]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

le.fit_transform(
    iris['species'].to_numpy() # it takes 1-D array
)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [23]:
from sklearn.model_selection import train_test_split

train_test_split(
    X,y, test_size=.2, random_state=1
)

[array([[0.0, 1.0, 2, 3, None, 6, 0, None],
        [1.0, 0.0, None, 3, 1, 6, 0, 4]], dtype=object),
 array([[1.0, 0.0, 2, 3, None, 6, 0, None]], dtype=object),
 array([3, 2]),
 array([1])]

# Feature Scaling

### Normalization
### Standardization

In [24]:
"""
Min-Max Norm.
MAx Abs Scaler.
Robust Scaler.
Standard Scaler (Z-Score).
"""

'\nMin-Max Norm.\nMAx Abs Scaler.\nRobust Scaler.\nStandard Scaler (Z-Score).\n'