In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import sklearn
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
iris = sns.load_dataset('iris')

In [4]:
y = iris['species']
iris.drop(['species'], inplace=True, axis=1)
X = iris

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.25, random_state=0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
from sklearn.svm import SVC

classifier = SVC(kernel='rbf', random_state=0)
classifier.fit(X_train, y_train)

SVC(random_state=0)

In [10]:
from sklearn.metrics import confusion_matrix, accuracy_score

y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


0.9736842105263158

In [11]:
# k-fold cross validation

In [12]:
from sklearn.model_selection import cross_val_score

In [13]:
classifier = SVC(kernel='rbf', random_state=0)

accuracies = cross_val_score(estimator=classifier, X=X_train, y=y_train, cv=10)

In [15]:
accuracies.mean()

0.9553030303030303

In [16]:
accuracies

array([1.        , 0.91666667, 0.90909091, 0.90909091, 1.        ,
       1.        , 1.        , 0.81818182, 1.        , 1.        ])

In [17]:
accuracies.std()

0.060459102129481135

In [18]:
accuracies.std() * 100

6.0459102129481135

In [19]:
from sklearn.model_selection import GridSearchCV

In [20]:
parameters = [
    {'C': [0.25, 0.5, 0.75, 1], 'kernel': ['linear']},
    {'C': [0.25, 0.5, 0.75, 1], 'kernel': ['rbf'], 'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]},
]

In [23]:
grid_search = GridSearchCV(
    estimator=classifier,
    param_grid=parameters,
    scoring='accuracy',
    cv=10,
    n_jobs=-1,
)

In [24]:
grid_search.fit(X_train, y_train)

GridSearchCV(cv=10, estimator=SVC(random_state=0), n_jobs=-1,
             param_grid=[{'C': [0.25, 0.5, 0.75, 1], 'kernel': ['linear']},
                         {'C': [0.25, 0.5, 0.75, 1],
                          'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8,
                                    0.9],
                          'kernel': ['rbf']}],
             scoring='accuracy')

In [25]:
grid_search.best_score_

0.9643939393939395

In [26]:
grid_search.best_params_

{'C': 1, 'gamma': 0.2, 'kernel': 'rbf'}

In [29]:
round(11.4)

11

In [28]:
round(11.5)

12